apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-deployment
  labels:
    app: cw2
spec:
  selector:
    matchLabels:
      app: cw2
  template:
    metadata:
      labels:
        app: cw2
    spec:
      containers:
      - name: cw2
        image: ngavan10/cw2
       

