apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-deployment
  labels:
    app: ngavan10/cw2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngavan10/cw2
  template:
    metadata:
      labels:
        app: ngavan10/cw2
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
       

