apiVersion: v1
kind: Service
metadata:
   name: cw2
   labels:
      k8s-app: cw2
spec:
   type: NodePort
   ports:
   - name: http
     port: 3000
     protocol: TCP
     targetPort: 3000
   selector:
     k8s-app: cw2
     component: nodejs
